name: Lint And Test Code Base
on:
  push:
    branches-ignore:
      - "main"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Setup Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "33.4"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Tidy Code Base
        run: |
          make tidy

      - name: Generate Code
        run: |
          make generate

      - name: Ensure Committed Code
        run: |
          git status --short
          git diff --quiet

      - name: Lint Code Base
        run: |
          make lint

      - name: Check Vulnerabilities
        run: |
          make vuln

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Setup Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "33.4"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Unit Test
        run: |
          make test
